format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character"""


add_newline=false

[line_break]
disabled=true

[battery]
disabled=true

[package]
disabled=true

[directory]
read_only = " "
truncation_length = 8
truncate_to_repo=false

[username]
style_user = "purple bold"
style_root = "red bold"
show_always = true

[character]
success_symbol = "[➜ ](bold green)"
error_symbol = "[➜ ](bold red)"
